### ISSUE TITLE
Adding new thresholds

### ISSUE THREAD

**Issue by smiles1969** [Cacti/plugin_thold#13]
Getting this error in apache error log adding new thresholds:

[Tue Sep 20 11:31:30.252623 2016] [:error] [pid 3915] [client 192.168.11.140:65526] script '/var/www/html/cacti/plugins/thold/graph_view.php' not found or unable to stat, referer: http://192.168.11.15/cacti/plugins/thold/thold.php?action=add

**Comment by cigamit** [comment]
that would definitely be a problem.  easy to track down though.

**Comment by cigamit** [comment]
Resolved here https://github.com/Cacti/plugin_thold/commit/fda2e6118629cafcd21ed4c7c70a8b93916f9395

**Comment by smiles1969** [comment]
Still getting this error after updating both cacti and thold plugin.

**Comment by smiles1969** [comment]
Also seeing this error in the log as well:


[Wed Sep 21 09:41:41.783613 2016] [:error] [pid 16143] [client 192.168.11.140:51960] PHP Notice:  Undefined index:  in /var/www/html/cacti/plugins/thold/thold_functions.php on line 1371, referer: http://192.168.11.15/cacti/plugins/thold/thold.php?action=ad

**Comment by smiles1969** [comment]
After comparing the thold.sql you provided. The keys for thold_data in the database created by the install script are not matching the keys in the .sql file. 

.sql file
  PRIMARY KEY (`id`),
  KEY `host_id` (`host_id`),
  KEY `rra_id` (`local_data_id`),
  KEY `data_id` (`data_template_rrd_id`),
  KEY `graph_id` (`local_graph_id`),
  KEY `template` (`thold_template_id`),
  KEY `thold_enabled` (`thold_enabled`),
  KEY `template_enabled` (`template_enabled`),
  KEY `tcheck` (`tcheck`)

actual cacti db
  PRIMARY KEY (`id`),
  KEY `host_id` (`host_id`),
  KEY `local_data_id` (`local_data_id`),
  KEY `data_template_rrd_id` (`data_template_rrd_id`),
  KEY `local_graph_id` (`local_graph_id`),
  KEY `thold_template_id` (`thold_template_id`),
  KEY `thold_enabled` (`thold_enabled`),
  KEY `template_enabled` (`template_enabled`),
  KEY `tcheck` (`tcheck`)

Yesterday I completely uninstalled and reinstalled the plugin, verifying that the table was dropped after uninstall. So I know this is not due to missing an update/change to the database along the way.

**Comment by cigamit** [comment]
doing a full regression now.  there are quite a few small issues.  the one above is minor and likely due to an upgrade.  the indexes are all there, but the names are a little different.  not a big deal.

**Comment by smiles1969** [comment]
Good to hear! This plugin is invaluable, thanks for all of your work...

**Comment by smiles1969** [comment]
Did you complete the regression by chance?
