### ISSUE TITLE
THOLD does not add new thresholds on 1.2.2 

### ISSUE THREAD

**Issue by Lalbee99** [Cacti/plugin_thold#275]
Describe the bug
I have upgraded my cacti from 0.8.8b to 1.2.2 with thold plugin version: 1.2.1 . I can create graphs which update perfectly fine. I can create and then see my thresholds under Management -> Thresholds for the host. I do not however see any thresholds for the host when looking under the THOLD tab.
To Reproduce
Create a device
Create Graphs for this Device
Auto-create Thresholds
Expected behavior
Screenshots
Desktop (please complete the following information):
OS: Windows 10
Browser Explorer Microsoft Edge
Version 38.14393.2068.0
Smartphone (please complete the following information):
Additional context

**Comment by Lalbee99** [comment]
General Information
Date Fri, 15 Mar 2019 13:44:35 -0400
Cacti Version 1.2.2
Cacti OS unix
RSA Fingerprint 83:6e:3c:63:23:d1:d1:7e:8b:1f:5f:f5:72:4d:75:8c
NET-SNMP Version NET-SNMP version: 5.7.2
RRDtool Version Configured 1.4.0+
RRDtool Version Found 1.4.8
Devices 178
Graphs 2563
Data Sources Script/Command: 387
SNMP Get: 130
SNMP Query: 1902
Script Query: 81
Script Server: 112
Total: 2612
Poller Information
Interval 300
Type SPINE 1.2.2 Copyright 2004-2017 by The Cacti Group
Items Action[0]: 4028
Action[1]: 660
Action[2]: 106
Total: 4794
Concurrent Processes 10
Max Threads 15
PHP Servers 5
Script Timeout 40
Max OID 60
Last Run Statistics Time:123.2908 Method:spine Processes:5 Threads:60 Hosts:158 HostsPerProcess:32 DataSources:4830 RRDsProcessed:0
System Memory
MemTotal 15.15 G
MemFree 1.96 G
MemAvailable 6.01 G
Buffers 378.03 M
Cached 3.90 G
Active 10.26 G
Inactive 2.44 G
SwapTotal 3.91 G
SwapFree 3.91 G
PHP Information
PHP Version 5.4.16
PHP Version 5.5.0+ is recommended due to strong password hashing support.
PHP OS Linux
PHP uname Linux cactiprd2 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64
PHP SNMP Installed
max_execution_time 60
memory_limit 1024M

**Comment by Lalbee99** [comment]
All pre-upgrade tholds are fine just any new ones

**Comment by Lalbee99** [comment]
Ran the following to make sure everything was sane with my database:
cli/analyze_database.php  (All Successful) 
cli/repair_database.php   (No Errors)
I have a development server running 1.1.37 w/THOLD version 1.05 with no issues

**Comment by Lalbee99** [comment]
One other note , you can create a single threshold from the graph with no problem. When you attempt to use the auto create it fails to add the threshold even though you get a successful confirmation.

**Comment by Lalbee99** [comment]
Another interesting tid bit I am able to manually dump the associated .rrd file and see values but when I attempt to do it from the graph in cacti no values.

**Comment by Lalbee99** [comment]
UPDATE:  I can now see thresholds with current values on new hosts if I choose "Thresholds" on the side menu panel but I cannot see anything for the new hosts if I choose the "THOLD" tab.

**Comment by Lalbee99** [comment]
There is clearly an code issue on the thold_graph.php when selecting thresholds from the THOLD tab. When showing thresholds via the side menu panel which runs thold.php it correctly renders.

**Comment by netniV** [comment]
Can you email a dump of your database to developers@cacti.net so that we can properly investigate with your data.  Also, if you can specify the id's of the thresholds that you see off the console menu, but not the thold top tab that would be useful for diagnosis.

**Comment by Lalbee99** [comment]
Sent

**Comment by vishnubraj** [comment]
even i am having the same issue.. its not able to create new thresholds.. Please let me know if you guys find a work around...

**Comment by netniV** [comment]
I have just updated the plugin, can you download v1.2.3 and let me know what you think.

**Comment by vishnubraj** [comment]
no @netniV  it's still not working..
also i see this in the device page..
<img width="1260" alt="Screenshot 2019-03-29 at 9 01 38 PM" src="https://user-images.githubusercontent.com/11851188/55243830-fbbaab00-5265-11e9-82fc-08ec9cb200a8.png">

**Comment by Lalbee99** [comment]
So the update did make my newer hosts thresholds appear in both the "Thresholds" on the side menu panel and the "THOLD" tab However now my older hosts only appear in the "Thresholds" side menu panel not in "THOLDS". It seems to have reversed the issue.

**Comment by netniV** [comment]
try
```sql
select td.id,td.name,td.name_cache,td.template_enabled as t_on, td.thold_template_id as t_id, tt.name as tt_name, tt.suggested_name as tt_suggest from thold_data td left join thold_template tt on tt.id = td.thold_template_id
```
you can limit it to specific data source id's by using
```sql
WHERE td.local_data_id IN (?,?,?)
```
replacing the question marks with different source ids.

**Comment by netniV** [comment]
And, I think we need to have two different issues here as you are NOT both experiencing the same problem.

**Comment by Lalbee99** [comment]
It appears on the ones I can see the thresholds in THOLD the name cache column is present and on my older ones the name cache column doers not exist. 

MariaDB [cacti]> select td.id,td.name,td.name_cache,td.template_enabled as t_on, td.thold_template_id as t_id, tt.name as tt_name, tt.suggested_name as tt_suggest from thold_data td left join thold_template tt on tt.id = td.thold_template_id WHERE td.local_data_id IN (24572);
+-------+-----------------------------------------------------+-------------------------------------+------+------+-----------------------------------------------+------------+
| id    | name                                                | name_cache                          | t_on | t_id | tt_name                                       | tt_suggest |
+-------+-----------------------------------------------------+-------------------------------------+------+------+-----------------------------------------------+------------+
| 15766 | wasprd4 - Filesystem Usage: - /data [hrStorageUsed] | wasprd4 - Filesystem Usage: - /data | on   |   60 | CHB Linux/Solaris Filesystems [hrStorageUsed] |            |
+-------+-----------------------------------------------------+-------------------------------------+------+------+-----------------------------------------------+------------+
1 row in set (0.00 sec)

MariaDB [cacti]> select td.id,td.name,td.name_cache,td.template_enabled as t_on, td.thold_template_id as t_id, tt.name as tt_name, tt.suggested_name as tt_suggest from thold_data td left join thold_template tt on tt.id = td.thold_template_id WHERE td.local_data_id IN (18936);
+-------+------+------------------------------------+------+------+-----------------------------------------------+------------+
| id    | name | name_cache                         | t_on | t_id | tt_name                                       | tt_suggest |
+-------+------+------------------------------------+------+------+-----------------------------------------------+------------+
| 14487 |      | wasprd9 - Filesystem Usage: - /var | on   |   60 | CHB Linux/Solaris Filesystems [hrStorageUsed] |            |
+-------+------+------------------------------------+------+------+-----------------------------------------------+------------+
1 row in set (0.00 sec)

**Comment by Lalbee99** [comment]
strike that, the older ones do not appear to have a name in the name column

**Comment by Lalbee99** [comment]
It seem that I have a lot of thresholds with the name field set to data_source_description.

**Comment by netniV** [comment]
They should have update during the latest update to have the same data source description template field. 

Any blank field for name_cache or where name = name_cache then it updates both during the upgrade.

**Comment by Lalbee99** [comment]
I went and corrected the issue with the name column being empty on the existing threshold. When I was finally at a place where all thresholds appeared in both the side panel Thresholds as well as the THOLD tab, I decided to add a new device. I then choose my graphs via the device page with no problem. I then choose "*Auto-create Thresholds" from the device page and once again I can see the thresholds in the side panel but not the THOLDS tab. I then ran a query in the database and noticed whenever the autocreate feature is used to create thresholds it does not populate the name column in thold_data.  This is consistent every time. 

MariaDB [cacti]> select name,name_cache,data_source_name from thold_data where name_cache LIKE "%extwebdev1%" ;
+------+----------------------------------------+------------------+
| name | name_cache                             | data_source_name |
+------+----------------------------------------+------------------+
|      | extwebdev1 Cpu                         | ssCpuIdle        |
|      | extwebdev1 - Filesystem Usage: - /     | hrStorageUsed    |
|      | extwebdev1 - Filesystem Usage: - /boot | hrStorageUsed    |
|      | extwebdev1 - Filesystem Usage: - /var  | hrStorageUsed    |
|      | extwebdev1 - Filesystem Usage: - /data | hrStorageUsed    |
+------+----------------------------------------+------------------+

**Comment by netniV** [comment]
Do you have the latest version?

**Comment by Lalbee99** [comment]
I have the newest you gave 1.2.3 THOLD

**Comment by Lalbee99** [comment]
THOLD 1.2.3

**Comment by TheWitness** [comment]
All, I've made a few updates.  For those of you using 1.2.3 already, please run the following database command, and then upgrade again.  Let us know if the issue is resolved there.

```sql
update plugin_config set version='1.2.2' where directory='thold';
```

**Comment by Lalbee99** [comment]
I did and got the following:
2019/03/31 09:00:04 - CMDPHP ERROR: A DB Exec Failed!, Error: Unknown column 'th.suggested_name' in 'field list'
2019/03/31 09:00:04 - CMDPHP SQL Backtrace:  (/plugins/thold/extras/upgrade.php[32]:thold_upgrade_database(), /plugins/thold/includes/database.php[1185]:db_execute(), /lib/database.php[189]:db_execute_prepared())

**Comment by Lalbee99** [comment]
Since I performed this upgrade when I create a threshold it does not appear in either the Thresholds in the side panel or the THOILD tab.  When the poller runs I get errors now:

2019/03/31 09:06:54 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/thold/thold.php[92]:autocreate(), /plugins/thold/thold_functions.php[4621]:thold_create_from_template(), /plugins/thold/thold_functions.php[4729]:thold_expand_title(), /plugins/thold/thold_functions.php[974]:CactiErrorHandler())
2019/03/31 09:06:54 - ERROR PHP WARNING in Plugin 'thold': Missing argument 5 for thold_expand_title(), called in /cacti/cacti-0.8.8b/plugins/thold/thold_functions.php on line 4729 and defined in file: /cacti/cacti-0.8.8b/plugins/thold/thold_functions.php on line: 974
2019/03/31 09:06:54 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/thold/thold.php[92]:autocreate(), /plugins/thold/thold_functions.php[4621]:thold_create_from_template(), /plugins/thold/thold_functions.php[4729]:thold_expand_title(), /plugins/thold/thold_functions.php[974]:CactiErrorHandler())
2019/03/31 09:06:54 - ERROR PHP WARNING in Plugin 'thold': Missing argument 4 for thold_expand_title(), called in /cacti/cacti-0.8.8b/plugins/thold/thold_functions.php on line 4729 and defined in file: /cacti/cacti-0.8.8b/plugins/thold/thold_functions.php on line: 974
2019/03/31 09:06:54 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/thold/thold.php[92]:autocreate(), /plugins/thold/thold_functions.php[4621]:thold_create_from_template(), /plugins/thold/thold_functions.php[4729]:thold_expand_title(), /plugins/thold/thold_functions.php[974]:CactiErrorHandler())
2019/03/31 09:06:54 - ERROR PHP WARNING in Plugin 'thold': Missing argument 3 for thold_expand_title(), called in /cacti/cacti-0.8.8b/plugins/thold/thold_functions.php on line 4729 and defined in file: /cacti/cacti-0.8.8b/plugins/thold/thold_functions.php on line: 974
2019/03/31 09:06:49 - CMDPHP PHP ERROR WARNING Backtrace: (/graphs_new.php[40]:form_save(), /graphs_new.php[126]:html_graph_new_graphs(), /lib/html_graph.php[447]:host_new_graphs_save(), /graphs_new.php[220]:create_save_graph(), /lib/template.php[1619]:create_complete_graph_from_template(), /lib/template.php[1321]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[221]:thold_create_graph_thold(), /plugins/thold/setup.php[1415]:autocreate(), /plugins/thold/thold_functions.php[4621]:thold_create_from_template(), /plugins/thold/thold_functions.php[4729]:thold_expand_title(), /plugins/thold/thold_functions.php[974]:CactiErrorHandler())
2019/03/31 09:06:49 - ERROR PHP WARNING in Plugin 'thold': Missing argument 5 for thold_expand_title(), called in /cacti/cacti-0.8.8b/plugins/thold/thold_functions.php on line 4729 and defined in file: /cacti/cacti-0.8.8b/plugins/thold/thold_functions.php on line: 974
2019/03/31 09:06:49 - CMDPHP PHP ERROR WARNING Backtrace: (/graphs_new.php[40]:form_save(), /graphs_new.php[126]:html_graph_new_graphs(), /lib/html_graph.php[447]:host_new_graphs_save(), /graphs_new.php[220]:create_save_graph(), /lib/template.php[1619]:create_complete_graph_from_template(), /lib/template.php[1321]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[221]:thold_create_graph_thold(), /plugins/thold/setup.php[1415]:autocreate(), /plugins/thold/thold_functions.php[4621]:thold_create_from_template(), /plugins/thold/thold_functions.php[4729]:thold_expand_title(), /plugins/thold/thold_functions.php[974]:CactiErrorHandler())
2019/03/31 09:06:49 - ERROR PHP WARNING in Plugin 'thold': Missing argument 4 for thold_expand_title(), called in /cacti/cacti-0.8.8b/plugins/thold/thold_functions.php on line 4729 and defined in file: /cacti/cacti-0.8.8b/plugins/thold/thold_functions.php on line: 974
2019/03/31 09:06:49 - CMDPHP PHP ERROR WARNING Backtrace: (/graphs_new.php[40]:form_save(), /graphs_new.php[126]:html_graph_new_graphs(), /lib/html_graph.php[447]:host_new_graphs_save(), /graphs_new.php[220]:create_save_graph(), /lib/template.php[1619]:create_complete_graph_from_template(), /lib/template.php[1321]:api_plugin_hook_function(), /lib/plugins.php[114]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[221]:thold_create_graph_thold(), /plugins/thold/setup.php[1415]:autocreate(), /plugins/thold/thold_functions.php[4621]:thold_create_from_template(), /plugins/thold/thold_functions.php[4729]:thold_expand_title(), /plugins/thold/thold_functions.php[974]:CactiErrorHandler())
2019/03/31 09:06:49 - ERROR PHP WARNING in Plugin 'thold': Missing argument 3 for thold_expand_title(), called in /cacti/cacti-0.8.8b/plugins/thold/thold_functions.php on line 4729 and defined in file: /cacti/cacti-0.8.8b/plugins/thold/thold_functions.php on line: 974

**Comment by TheWitness** [comment]
Okay, this is my bad.  I've just done another commit.  Please let me know if it's settled now.

**Comment by Lalbee99** [comment]
I installed the latest THOLD and there were no errors in the cacti log from the upgrade.  The poller appears to run error free. I then added a threshold via the device's *Auto-create Thresholds and the threshold shows in the Thresholds side panel but not the THOLD tab. I then queried the database for the threshold  (swap space). 
MariaDB [cacti]> select name,name_cache,data_source_name from thold_data where name_cache LIKE "%spaceprd2%" ;
+-------------------------------------------------------+--------------------------------------------+------------------+
| name                                                  | name_cache                                 | data_source_name |
+-------------------------------------------------------+--------------------------------------------+------------------+
| spaceprd2 - Filesystem Usage: - / [hrStorageUsed]     | spaceprd2 - Filesystem Usage: - /          | hrStorageUsed    |
| spaceprd2 - Filesystem Usage: - /boot [hrStorageUsed] | spaceprd2 - Filesystem Usage: - /boot      | hrStorageUsed    |
| spaceprd2 - Filesystem Usage: - /var [hrStorageUsed]  | spaceprd2 - Filesystem Usage: - /var       | hrStorageUsed    |
| spaceprd2 - Filesystem Usage: - /data [hrStorageUsed] | spaceprd2 - Filesystem Usage: - /data      | hrStorageUsed    |
| spaceprd2 - RHEL Memory [ChbRhelUsed]                 | spaceprd2 - RHEL Memory                    | ChbRhelUsed      |
| spaceprd2 Cpu [ssCpuIdle]                             | spaceprd2 Cpu                              | ssCpuIdle        |
| |data_source_description|                             | spaceprd2 - Filesystem Usage: - Swap space | hrStorageUsed    |
+-------------------------------------------------------+--------------------------------------------+------------------+

**Comment by TheWitness** [comment]
Well, from the Thold tab, can you verify that the status is all thresholds if it does not show then, note the thold's id and then run the following:

```shell
SELECT * FROM thold_data WHERE id = ?\G
```
Post the results.

**Comment by TheWitness** [comment]
One thing that I don't know about the naming as is, is that the 'name' column should be '|data_source_description|' all the time.  The fact that it's the originally replaced name, means that in future saves, the name cache will get messed up names.  Also, if the suggested name of the data source is changed, the thold will not follow suite.  Therefore, I'm toying with the idea of making  updating the name to always be |data_source_name|.  I'm just not settled on that yet though.

**Comment by netniV** [comment]
In my view, there should be three scenario's.

* _Non Templated_

   The name should be editable directly on the threshold, with a default of |data_source_description|

* _Templated, with propagation_

   The name should be editable on the template only.  The template suggested name  should allow for customisation as there are times you want a different title, not just what is used by the data source.  For example, you may prefix templates with a site name and all thresholds created for a site used that template to get: Site - |data_source_description|

   Any changes to the suggested name should be pushed out.

   Again the default suggested name should be |data_source_description|

* _Template, with propagation disabled_

   The name should have originally come from the template, as per above, but be editable as per the non-templated version.  If propagation is turned on, any customised would be lost and the template would once more reign supreme.

In all cases any update to the name/suggested name should repopulate the name_cache.  It would also be good if an update to the data source name or other values that can be substituted also cause a refresh of the name cache.

**Comment by Lalbee99** [comment]
Interesting.... So I went into THOLDS and set it to all devices , I then sorted by name and low an behold I see the swap space threshold for my device spaceprd2. When I use search and give it the hostname spaceprd2 I do not see the swap space threshold in the list of thresholds returned.   

MariaDB [cacti]> SELECT * FROM thold_data WHERE id = 15838\G
*************************** 1. row ***************************
                         id: 15838
                       name: |data_source_description|
                 name_cache: spaceprd2 - Filesystem Usage: - Swap space
              local_data_id: 24673
       data_template_rrd_id: 57236
             local_graph_id: 21191
          graph_template_id: 273
         data_template_hash:
           data_template_id: 288
           data_source_name: hrStorageUsed
                   thold_hi: 80
                  thold_low:
         thold_fail_trigger: 3
                    time_hi:
                   time_low:
          time_fail_trigger: 1
           time_fail_length: 1
           thold_fail_count: 0
                thold_alert: 0
           prev_thold_alert: 0
              thold_enabled: on
                 thold_type: 0
          bl_ref_time_range: 1800
                bl_pct_down: 20
                  bl_pct_up: 20
            bl_fail_trigger: 3
              bl_fail_count: 0
                   bl_alert: 0
                   lastread: 0
                   lasttime: 2019-03-31 16:45:05
                   oldvalue: 0
               repeat_alert: 6
               notify_extra: isdsystems@tch.harvard.edu,1852@pagemail.tch.harvard.edu
                    host_id: 613
            syslog_priority: NULL
            syslog_facility: NULL
             syslog_enabled:
                  data_type: 2
                       cdef: 0
                 percent_ds: hrStorageSize
                 expression:
          thold_template_id: 60
           template_enabled: on
                     tcheck: 1
                     exempt: off
             acknowledgment:
          thold_hrule_alert: NULL
        thold_hrule_warning: NULL
             restored_alert: off
                  reset_ack: off
                persist_ack: off
                 email_body: A warning has been issued that requires your attention. <br><br><strong>Device</strong>: <DESCRIPTION> (<HOSTNAME>)<br><strong>URL</strong>: <URL><br><strong>Message</strong>: <SUBJECT><br><br><GRAPH>
            email_body_warn: A warning has been issued that requires your attention. <br><br><strong>Device</strong>: <DESCRIPTION> (<HOSTNAME>)<br><strong>URL</strong>: <URL><br><strong>Message</strong>: <SUBJECT><br><br><GRAPH>
           trigger_cmd_high:
            trigger_cmd_low:
           trigger_cmd_norm:
               exempt_state: NULL
          exempt_begin_time: NULL
            exempt_end_time: NULL
   time_warning_fail_length: 1
           thold_warning_hi:
          thold_warning_low:
   thold_warning_fail_count: 0
            time_warning_hi:
           time_warning_low:
  time_warning_fail_trigger: 1
       notify_warning_extra:
             notify_warning: 0
               notify_alert: 1
 thold_warning_fail_trigger: 2
             bl_thold_valid: 0
        snmp_event_category: NULL
        snmp_event_severity: 3
snmp_event_warning_severity: 2
           thold_daemon_pid:
                      notes:
1 row in set (0.00 sec)

**Comment by Lalbee99** [comment]
Seems like search is based on a the name column which is data_source_description on my new threshold. All my older thresholds do not have this: 
MariaDB [cacti]> select name,name_cache,data_source_name from thold_data where name_cache LIKE "%spaceprd2%" ;
+-------------------------------------------------------+--------------------------------------------+------------------+
| name                                                  | name_cache                                 | data_source_name |
+-------------------------------------------------------+--------------------------------------------+------------------+
| spaceprd2 - Filesystem Usage: - / [hrStorageUsed]     | spaceprd2 - Filesystem Usage: - /          | hrStorageUsed    |
| spaceprd2 - Filesystem Usage: - /boot [hrStorageUsed] | spaceprd2 - Filesystem Usage: - /boot      | hrStorageUsed    |
| spaceprd2 - Filesystem Usage: - /var [hrStorageUsed]  | spaceprd2 - Filesystem Usage: - /var       | hrStorageUsed    |
| spaceprd2 - Filesystem Usage: - /data [hrStorageUsed] | spaceprd2 - Filesystem Usage: - /data      | hrStorageUsed    |
| spaceprd2 - Swap [memAvailSwap]                       | spaceprd2 - Swap                           | memAvailSwap     |
| spaceprd2 - RHEL Memory [ChbRhelUsed]                 | spaceprd2 - RHEL Memory                    | ChbRhelUsed      |
| spaceprd2 Cpu [ssCpuIdle]                             | spaceprd2 Cpu                              | ssCpuIdle        |
| |data_source_description|                             | spaceprd2 - Filesystem Usage: - Swap space | hrStorageUsed    |
+-------------------------------------------------------+--------------------------------------------+------------------+

**Comment by TheWitness** [comment]
Okay, found that most recent bug.  It's not searching the name_cache column as it should.  Still reviewing your other comments.

**Comment by TheWitness** [comment]
@netviV, all is working except for the reapply suggested names, which I'll be implementing shortly.  It'll be automatic.  Right now, it's not.

**Comment by TheWitness** [comment]
@netniV, okay push out now modifying the name cache on Template save as expected.

**Comment by TheWitness** [comment]
@Lalbee99, I'm going to close this ticket.  Please open a new one for any outstanding issues.  This thread has covered too many cases.  Better open another ticket.

**Comment by Lalbee99** [comment]
Was it resolved?

**Comment by Lalbee99** [comment]
I just loaded 1.2.4 and it does work thank you. One last question I noticed the name column is data_source_description is this suppose to be consistent across all thresholds. My older ones have the actual name (see below). Should I change them?
+-------------------------------------------------------+--------------------------------------------+------------------+
| name                                                  | name_cache                                 | data_source_name |
+-------------------------------------------------------+--------------------------------------------+------------------+
| spaceprd2 - Filesystem Usage: - / [hrStorageUsed]     | spaceprd2 - Filesystem Usage: - /          | hrStorageUsed    |
| spaceprd2 - Filesystem Usage: - /boot [hrStorageUsed] | spaceprd2 - Filesystem Usage: - /boot      | hrStorageUsed    |
| spaceprd2 - Filesystem Usage: - /var [hrStorageUsed]  | spaceprd2 - Filesystem Usage: - /var       | hrStorageUsed    |
| spaceprd2 - Filesystem Usage: - /data [hrStorageUsed] | spaceprd2 - Filesystem Usage: - /data      | hrStorageUsed    |
| spaceprd2 - Swap [memAvailSwap]                       | spaceprd2 - Swap                           | memAvailSwap     |
| spaceprd2 - RHEL Memory [ChbRhelUsed]                 | spaceprd2 - RHEL Memory                    | ChbRhelUsed      |
| spaceprd2 Cpu [ssCpuIdle]                             | spaceprd2 Cpu                              | ssCpuIdle        |
| |data_source_description|                             | spaceprd2 - Filesystem Usage: - Swap space | hrStorageUsed    |

**Comment by TheWitness** [comment]
I would, it prevents auto-renaming when you make changes.  I was just concerned about possible backlash.  To rename, do the following:

```shell
UPDATE thold_data SET name='|data_source_description|' WHERE name != '|data_source_description|';
```

Then push out all your Thresholds.

**Comment by TheWitness** [comment]
So, before we tag this release, I want to make sure it's bug free.  I may add this change before the official release, so if you find anything in the next few days, it's important to report the issues right away.

**Comment by Lalbee99** [comment]
Thx, What exactly is meant by "push out all your thresholds"

**Comment by TheWitness** [comment]
"Reapply Suggested Names"

**Comment by TheWitness** [comment]
Sorry, "push out" a Cacti developer would understand.  Shop talk.

**Comment by Lalbee99** [comment]
I performed both steps and everything is OK. I will let you know if I see anything abnormal going forward.
