### ISSUE TITLE
When saving a template, notification lists of all templates are updated

### ISSUE THREAD

**Issue by stormonts** [Cacti/plugin_thold#369]
We are running Cacti 1.2.4 and Thold 1.2.4.

If we create a new threshold template, the email notification fields in all existing templates are changed to whatever is specified in that new template.  If we edit the e-mail notification in an existing template, the same behavior happens to all other existing templates.  Another user had the same issue and reported it here: https://forums.cacti.net/viewtopic.php?f=17&t=60004

**Comment by stormonts** [comment]
I was running Cacti 1.2.4 and thold 1.2.4 when I submitted this.  I have now updated to Cacti 1.2.6 and thold 1.3.2 and the same behavior exists.

**Comment by netniV** [comment]
OK, thanks for the update.  I'll try and take a look to see if I can spot something obvious.

**Comment by stormonts** [comment]
Did you have a chance to look into this?

**Comment by netniV** [comment]
I did a quick test and didn't manage to reproduce it, need some more time to properly go through things.

**Comment by stormonts** [comment]
What version of Thold and Cacti did you try it on?  We are now on Cacti 1.2.8 and I am wondering if it may have been fixed (we have been afraid to test given the amount of work re-creating all thresholds causes).

**Comment by netniV** [comment]
Ah, yes.  If you were on 1.2.7, I think there was a nasty form bug that was resolved.  Please give it a try (though don't do too many) and see what happens.

**Comment by stormonts** [comment]
We were on Cacti 1.2.4 and 1.2.6 when I reported the issue.  Unfortunately, even changing the settings of just 1 threshold would change all of them.   We'll give it a try and see what happens in 1.2.8 now.

**Comment by stormonts** [comment]
Sadly, the same issue still exists for me on 1.2.8.  I just created a brand new threshold template, and the "Warning Notification List" and "Alert Notification List" of all existing thresholds is changed to whatever group was specified in the new threshold template.

**Comment by netniV** [comment]
OK, I will take a look into this since it seems easy to reproduce.

**Comment by stormonts** [comment]
As a summary:
Cacti 1.2.8
Thold 1.3.2

1. Have an existing threshold template (we made one based off of Host MIB - Hard Drive Space) that has a group defined in the "Warning Notification List" and "Alert Notification List" boxes.  Create threshold from the template. 
2. Create a brand new threshold template (we made one based off of Interface - Traffic), define groups in the "Warning Notification List" and "Alert Notification List" boxes. Save the template.
3. Manage -> Thresholds and then select any existing threshold.  The group defined in the two Notification List boxes has been changed to what was configured when the new template was made.

**Comment by netniV** [comment]
I can confirm that this bug can be replicated.  the notify_warn and notify_alert fields were updated.  As was thold_alert which is the type of alert.  This suggests that the template push out code is not limiting itself to its own thresholds.

**Comment by netniV** [comment]
This should now been fixed.
