### ISSUE TITLE
PHP Notice: Undefined index: thold_draw_vrules in setup.php line 176

### ISSUE THREAD

**Issue by cypherstream** [Cacti/plugin_thold#41]
Hello,
Recently upgraded to Cacti 1.0.1 and thold 1 via git clone.  I did apply the patch to fix issue 39 and I was able to setup all my thresholds to allow email alerting under specific conditions on particular interfaces.  It appears as if that is working, however when diagnosing a separate issue in Cacti I notice at every graph page load the following is written to the apache2/error.log file:

[Thu Feb 02 09:45:17.824628 2017] [:error] [pid 17524] [client 10.7.3.7:61135] PHP Notice:  Undefined index: thold_draw_vrules in /var/www/cacti/plugins/thold/setup.php on line 176, referer: http://intranet/cacti/graph_view.php?action=tree&node=tbranch-313&hyper=true

I then tested the toggle threshold vrules on for some graphs and I did not see any changes to the graphs, so maybe in fact there is an issue here beyond a slightly chatty apache error.log.

Line 176 of setup.php is:
` print '<a class="iconLink" href="' .  $url . $separator . 'thold_vrule=' . ($_SESSION['sess_config_array']['thold_draw_vrules'] == 'on' ? 'off' : 'on') . '"><img src="' . $config['url_path'] . 'plugins/thold/images/reddot.png" border="0" alt="" title="' . __('Toggle Threshold VRULES %s', ($_SESSION['sess_config_array']['thold_draw_vrules'] == 'on' ? __('Off') : __('On'))) . '"></a><br>';`

**Comment by cigamit** [comment]
This issue is resolved.  If the VRULES do not show up when you enable the feature, please open another issue.

**Comment by cypherstream** [comment]
syn'd up from git and only the readme changed and the three issues from patch 39 (after stashing my pre-committed patch).  Still an issue, will investigate more and possibly open an issue.  Not sure how to "enable the feature" only H rules appear in creating thresholds and the graph icon toggle threshold vrules on does nothing.  Trying to figure out if its me understanding a feature wrong before submitting an issue.  Maybe its me...

**Comment by cigamit** [comment]
Please review the image below.  Red indicates Alert threshold breach, Orange a Warning thershold breach, and Green, a return to normal.

I hope that helps.  I am about to commit a change that corrects some issues that were being experienced showing the right colors.

<img width="490" alt="tholdvrules" src="https://cloud.githubusercontent.com/assets/957322/22615210/bcb65096-ea55-11e6-9de0-c7336b5bd2f5.png">
