### ISSUE TITLE
Upgrade on CentOS 7.9 for PHP 7.2 to 7.4 caused Cacti issues 

### ISSUE THREAD

**Issue by pnkdoshi** [Cacti/plugin_thold#501]
**Describe the bug**
I installed cacti a month or so back using the tar file. Its running at version 1.2.15. We did a upgrade on our for PHP from 7.2 to 7.4. Right after that the reports/ thold /Web Service Checks stopped working. Basically it looks like the poller can't run. I have tried troubleshooting this for the last few hours and I am not making any good progress. I see online there are similar complaints about the upgrades but they don't seem to be the exact issue I had. I'm hoping this is a bug or if not, someone can point me in the right direction. 

**To Reproduce**
These are the errors I am seeing in the cacti logs and happen when I run the poller.php script 
2021-03-24 23:21:01 - ERROR PHP NOTICE: Trying to access array offset on value of type bool in file: /usr/share/cacti/lib/snmpagent.php  on line: 302
2021-03-24 23:21:01 - CMDPHP PHP ERROR NOTICE Backtrace:  (/poller.php[705]:snmpagent_poller_exiting(), /lib/snmpagent.php[302]:CactiErrorHandler())
2021-03-24 23:21:01 - ERROR PHP NOTICE: Trying to access array offset on value of type bool in file: /usr/share/cacti/lib/snmpagent.php  on line: 303
2021-03-24 23:21:01 - CMDPHP PHP ERROR NOTICE Backtrace:  (/poller.php[705]:snmpagent_poller_exiting(), /lib/snmpagent.php[303]:CactiErrorHandler())
2021-03-24 23:21:01 - SNMPAGENT WARNING: No notification receivers configured for event: cactiNotifyPollerRuntimeExceeding (CACTI-MIB), severity: high
2021-03-24 23:21:01 - SYSTEM STATS: Time:298.8632 Method:cmd.php Processes:1 Threads:0 Hosts:17 HostsPerProcess:17 DataSources:71 RRDsProcessed:0
2021-03-24 23:21:01 - SYSTEM THOLD STATS: Time:0.1208 Tholds:0 TotalDevices:17 DownDevices:0 NewDownDevices:0
2021-03-24 23:25:01 - POLLER: Poller[1] Maximum runtime of 298 seconds exceeded. Exiting.

**Expected behavior**
Poller should run without fail after a 7.4 upgrade. 

**Screenshots**

**Plugin (please complete the following information):**
 - Cacti Version: 1.2.15
 - Source: https://www.cacti.net/download_cacti.php
 - Plugins Version: 

Maintenance Scheduler v1.2
Thresholds v1.5.3
Web Service Monitor v3.0

**Desktop (please complete the following information):**
 - OS: CentOS Linux release 7.9.2009 (Core)

**Comment by bmfmancini** [comment]
@TheWitness  @netniV  @cigamit  can you move this to the Main Cacti issues page  this does not seems thold related

**Comment by bmfmancini** [comment]
@pnkdoshi  can you try pulling /lib/snmpagent.php from the 1.2.x branch

**Comment by bmfmancini** [comment]
Use this URL to do a wget make a backup of the original file and try this one 
https://raw.githubusercontent.com/Cacti/cacti/1.2.x/lib/snmpagent.php

**Comment by cigamit** [comment]
This is for an older version of Cacti, and I believe everything for PHP 7.4 was already fixed in 1.2.16. Unless it can be demonstrated on the latest version of Cacti, this should be closed IMO.

**Comment by TheWitness** [comment]
I'm wondering where he got PHP7.4 from.  Is that available in SCL?

**Comment by pnkdoshi** [comment]
I did the wget on the snmpagent file and did a vimdiff, on the backup. They are exactly the same except for the copyright dates being updated. 
Still getting the same errors when I run poller.php 

We got PHP 7.4 from here
yum-config-manager --enable remi-php74
yum install php

**Comment by TheWitness** [comment]
See if you use php7.3, if the problem goes away.  Are you using the snmp agent?

**Comment by TheWitness** [comment]
Also, note you have to update more than just that file.  The is in the include/vendor directory a mib parser library, and another mib file in lib.  So, update all three.

**Comment by pnkdoshi** [comment]
Thank you all for the time on this. I believe I have figured it out. I will try to leave a detail explanation for the next person. I also have one more question if you can help me out with it. 

1. We installed PHP 7.4. 
yum-config-manager --enable remi-php74
yum install php
2. The install put a php bin file in a new directory /usr/bin/php. The old location was /usr/local/bin/php. Cacti had that old path in its settings. For some reason the install did not delete the old php file but I have to assume the yum install broke how the old one was working. 
3. I manually removed the /usr/local/bin/php file. Updated the db table settings path_php_binary with the new location. 
4. I restarted apache  / server and for some reason the reports were still failing but the errors above went away. 
5. I saw in the cacti logs that the poller.php was still executing the old php path. I put a symlink in there for now (ln -s /usr/bin/php /usr/local/bin/php)
 /usr/local/bin/php -q /usr/share/cacti/scripts/ss_get_by_ssh.php --host '10.10.10.112' --type df --items nj,nk --volume '/dev/sda2',
6. After all those above changes , my reports are seeing data again. 

QUESTION: Where else would the php path be getting set?  I did search in the cacti directory for /usr/local/bin/php and I also did a mysqldump of the cacti db and searched for the same string.

**Comment by TheWitness** [comment]
If my memory serves me right, poller.php will force set it if the path provided does not exist.  I tried SCL, but ended up using remi as it requires the least work.

**Comment by TheWitness** [comment]
There are two ways to set it, in the poller.php and forcing it in config.php.  The later depends on your cacti version.

**Comment by pnkdoshi** [comment]
Thanks again everyone. Looks like the issue was on my end not Cacti. I will try to find out why the old file is still being referenced and let everyone know how to fix that. I did update it in the config but its still not taking and now I am more interested in why for me. I will go ahead and close this issue.
