### ISSUE TITLE
Automatically creating thresholds creates numerous thresholds

### ISSUE THREAD

**Issue by stormonts** [Cacti/plugin_thold#58]
I am having an issue with all version of Cacti 1.x.  I have made a threshold for hard drive space that is supposed to fire at 80%. When I apply the threshold rule to any device, there are 7 thresholds that get created and only one of them matches the rule that I have created.

![specific](https://cloud.githubusercontent.com/assets/25824323/23835009/25d717b6-0736-11e7-85e5-4a4bb435b20e.png)
![space threshold](https://cloud.githubusercontent.com/assets/25824323/23835011/280eb20a-0736-11e7-8cba-272c076e81bf.png)

**Comment by cigamit** [comment]
So, delete them all, and then document the exact process you use to make them all appear again.  Okay?  You still have not documented the problem.  So, to be clear:

1) Delete all thresholds associated with that device
2) Take screen show of your example above showing no thresholds.
3) Follow the process you used before to create them.  Document exact steps
4) Show the screen shit with the 7 created again.
5) Show Threshold Template page with no filters.

So, that means you will give me three screen shots, one step by step process.

**Comment by stormonts** [comment]
Device util-st-01 exists in Cacti 1.0.4 with no thresholds created.
(from Management -> Thresholds)![1_no_thresholds for util-st-01](https://cloud.githubusercontent.com/assets/25824323/23835867/284d8a48-0745-11e7-90a8-d413d63aedcc.png)

From Management -> Device ![2_no_thresholds for util-st-01](https://cloud.githubusercontent.com/assets/25824323/23835868/2d756df6-0745-11e7-84af-d95e5dc42516.png)
In Management -> Devices, I put a check in the box next to util-st-01. then select "Apply Thresholds" from the drop down and click Go.  The "Linux Hard Drive Space Utilization (80% utilization)" is associated with the server as noted in the screenshot above, so I would expect 1 threshold to be made using the settings in that threshold.

Settings in "Linux Hard Drive Space Utilization (80% utilization)" threshold![specific](https://cloud.githubusercontent.com/assets/25824323/23835888/7fbeb6bc-0745-11e7-8e78-46ec9b808fdb.png)
Instead, when I go to management -> Thresholds, I see multiple thresholds created for that device in addition to the one that I was expecting.
![3_7 thresholds](https://cloud.githubusercontent.com/assets/25824323/23835902/b4311a98-0745-11e7-9cfc-97a5821b0b12.png)

**Comment by cigamit** [comment]
Please re-read my request.  You have not answered all my question.  Also, for the device template in question, show the device template's threshold template location.

**Comment by stormonts** [comment]
I'm, sorry, but I'm really not sure what else you need.  I don't understand what you mean by "the device template's threshold template location".  Everything is in the default paths as specified by Cacti.

1) Log into Cacti
2) Create a new threshold, by clicking on Templates -> Threshold -> Add
![new threshold](https://cloud.githubusercontent.com/assets/25824323/23839237/f6c1a2d8-0772-11e7-80ef-e2e437ac9e54.png)
3) Click on Template -> Device -> Add
4) Give the template a name (Linux Server), click Add.
5) Select the graph templates to associate (I choose ucd/net Memory Usage and Load average).
6) Select the associated Data queries (I choose Fridh ucd/net - Systemstats, SNMP get Mounted partitions, SNMP interface statistics)
7) Select the Associated Threshold templates and I choose "Linux Hard Drive Space utilization (80% utilization)" as created in step #2.
8) Click Save
![device_template](https://cloud.githubusercontent.com/assets/25824323/23839539/1e1f5990-0775-11e7-9cd9-2a4fde777531.png)
9) At this point, there are no thresholds that have been created for this server.
![1_no_thresholds for util-st-01](https://cloud.githubusercontent.com/assets/25824323/23839573/641ce804-0775-11e7-8aab-bb0d78877865.png)
10) Click on Device, then Add
11) Add a new device and select the "Linux Server" template created in Step #4.
12) Click Save, then click Return after the device has been saved.
13) In Management -> Devices, put a check in the box next to the new server, then select "Apply Thresholds" from the drop down and click Go. 
14) Click on Management -> Thresholds and there are now multiple thresholds created for the hard drive space usage instead of just the one expected that should have been created by the template.
![space threshold](https://cloud.githubusercontent.com/assets/25824323/23839610/ad91ccb6-0775-11e7-91c7-52ddc68c3d20.png)

**Comment by cigamit** [comment]
You still have not shown me the threshold templates page.  That's the important one.

**Comment by stormonts** [comment]
Is this the screen you are looking for?
![templates](https://cloud.githubusercontent.com/assets/25824323/24061241/0376004c-0b2d-11e7-945f-0240101f05f2.png)

The only threshold that i have associated with a Linux device is the 80% one.

![templates2](https://cloud.githubusercontent.com/assets/25824323/24061294/3d0a46ce-0b2d-11e7-9f3e-3ac30936dc24.png)

**Comment by cigamit** [comment]
Yup, that tells the whole story.  Should not be too difficult to fix.  Just needed the verification on the root cause.

**Comment by cigamit** [comment]
Resolved, please test.

**Comment by stormonts** [comment]
Thanks.  Sorry it took me so long to figure out which image you needed.

**Comment by jzpx** [comment]
Hello, I'm experiencing this issue on Cacti 1.1.12. I see that this has been fixed supposedly on thold v1.0.1 but I've tried that up to v1.0.6 and I'm still having this issue.

**Comment by netniV** [comment]
That version of both Cacti and Thold are well outdated.  You should update both.

**Comment by jzpx** [comment]
> That version of both Cacti and Thold are well outdated. You should update both.

I just updated, now on Cacti 1.2.4 with thold 1.3.2 and issue/bug persists.

**Comment by jmedina17** [comment]
cual fue la solución del problema @cigamit, me podrías indicar
