### ISSUE TITLE
Thold disabled due to error: ERROR PHP PARSE in Plugin 'thold': syntax error, unexpected '*' in file: /var/www/html/plugins/thold/thold_functions.php(200) : eval()'d code on line: 1

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_thold#99]
After creating "automated" thresholds for a device I have encountered an issue below where THOLD gets disabled due to error in plugin.

![thold-errors](https://user-images.githubusercontent.com/11211789/28122204-7fcaef26-66eb-11e7-86f4-4627adee3a16.gif)

2017/07/12 10:08:31 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'thold'
2017/07/12 10:08:31 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4430 cacti_debug_backtrace)
2017/07/12 10:08:31 - ERROR PHP PARSE in Plugin 'thold': syntax error, unexpected '*' in file: /var/www/html/plugins/thold/thold_functions.php(200) : eval()'d code on line: 1
2017/07/12 10:08:21 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php: 518 process_poller_output)(/lib/poller.php: 510 api_plugin_hook_function)(/lib/plugins.php: 105 api_plugin_run_plugin_hook_function)(/lib/plugins.php: 206 thold_poller_output)(/plugins/thold/includes/polling.php: 200 thold_calculate_expression)(/plugins/thold/thold_functions.php: 748 thold_expression_math_rpn)(/plugins/thold/thold_functions.php: 200 eval)(/plugins/thold/thold_functions.php(200) : eval()'d code: 1 CactiErrorHandler)(/lib/functions.php: 4387 cacti_debug_backtrace)
2017/07/12 10:08:21 - ERROR PHP WARNING in Plugin 'thold': Division by zero in file: /var/www/html/plugins/thold/thold_functions.php(200) : eval()'d code on line: 1
2017/07/12 10:08:21 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php: 518 process_poller_output)(/lib/poller.php: 510 api_plugin_hook_function)(/lib/plugins.php: 105 api_plugin_run_plugin_hook_function)(/lib/plugins.php: 206 thold_poller_output)(/plugins/thold/includes/polling.php: 200 thold_calculate_expression)(/plugins/thold/thold_functions.php: 748 thold_expression_math_rpn)(/plugins/thold/thold_functions.php: 200 eval)(/plugins/thold/thold_functions.php(200) : eval()'d code: 1 CactiErrorHandler)(/lib/functions.php: 4387 cacti_debug_backtrace)
2017/07/12 10:08:21 - ERROR PHP WARNING in Plugin 'thold': Division by zero in file: /var/www/html/plugins/thold/thold_functions.php(200) : eval()'d code on line: 1
2017/07/12 10:08:14 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php: 533 process_poller_output)(/lib/poller.php: 510 api_plugin_hook_function)(/lib/plugins.php: 105 api_plugin_run_plugin_hook_function)(/lib/plugins.php: 206 thold_poller_output)(/plugins/thold/includes/polling.php: 200 thold_calculate_expression)(/plugins/thold/thold_functions.php: 748 thold_expression_math_rpn)(/plugins/thold/thold_functions.php: 200 eval)(/plugins/thold/thold_functions.php(200) : eval()'d code: 1 CactiErrorHandler)(/lib/functions.php: 4387 cacti_debug_backtrace)
2017/07/12 10:08:14 - ERROR PHP WARNING in Plugin 'thold': Division by zero in file: /var/www/html/plugins/thold/thold_functions.php(200) : eval()'d code on line: 1
2017/07/12 10:08:14 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php: 533 process_poller_output)(/lib/poller.php: 510 api_plugin_hook_function)(/lib/plugins.php: 105 api_plugin_run_plugin_hook_function)(/lib/plugins.php: 206 thold_poller_output)(/plugins/thold/includes/polling.php: 200 thold_calculate_expression)(/plugins/thold/thold_functions.php: 748 thold_expression_math_rpn)(/plugins/thold/thold_functions.php: 200 eval)(/plugins/thold/thold_functions.php(200) : eval()'d code: 1 CactiErrorHandler)(/lib/functions.php: 4387 cacti_debug_backtrace)
2017/07/12 10:08:14 - ERROR PHP WARNING in Plugin 'thold': Division by zero in file: /var/www/html/plugins/thold/thold_functions.php(200) : eval()'d code on line: 1

**Comment by cigamit** [comment]
Should be resolved now.  Though ti's likely your RPN was not valid.

**Comment by ikorzha** [comment]
Unfortunately I'm forced to acknowledge that proposed fix didn't solve the problem:
Same msgs below...


2017/09/01  22:40:11 - ERROR PHP PARSE in  Plugin 'thold': syntax error, unexpected  '*' in file: /var/www/html/plugins/thold/thold_functions.php(201) :  eval()'d code on line: 1
--
2017/09/01 22:40:10 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'thold'
2017/09/01 22:40:10 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4459 cacti_debug_backtrace)
2017/09/01 22:40:10 - ERROR PHP PARSE in   Plugin 'thold': syntax error, unexpected '*' in file:  /var/www/html/plugins/thold/thold_functions.php(201) : eval()'d code on  line: 1
2017/09/01 22:40:10 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'thold'
2017/09/01 22:40:09 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4459 cacti_debug_backtrace)
2017/09/01 22:40:09 - ERROR PHP PARSE in   Plugin 'thold': syntax error, unexpected '*' in file:  /var/www/html/plugins/thold/thold_functions.php(201) : eval()'d code on  line: 1

**Comment by ikorzha** [comment]
Cigiamit, I have tested attempt #2 for fix 99, it is a lot better than before thold no longer gets disabled, but I have huge number of expression errors in the log.

It appears to be new fix is unable to handle expression results of 0 and results from logical interfaces such as bond....
Please see below.


2017/09/02  08:15:22 - THOLD ERROR: RPN Expression is invalid!  THold:'E1Z05R0848-VDX6740T-A - Traffic - 10.255.4.119 - eth0  [traffic_in]', Value:'0',  Expression:'\|ds:traffic_in\|,8,*,1000000,/,\|query_ifHighSpeed\|,/,100,*'
--
2017/09/02 08:15:22 - THOLD ERROR: RPN  Expression is invalid! THold:'E1Z07R0848-VDX6740T-A - Traffic -  10.255.4.133 - eth0 [traffic_in]', Value:'0',  Expression:'\|ds:traffic_in\|,8,*,1000000,/,\|query_ifHighSpeed\|,/,100,*'
2017/09/02 08:15:22 - THOLD ERROR: RPN  Expression is invalid! THold:'E1T14 NX7010 CORE1 - Traffic - Null0  [traffic_out]', Value:'0',  Expression:'\|ds:traffic_out\|,8,*,1000000,/,\|query_ifHighSpeed\|,/,100,*'
2017/09/02 08:15:22 - THOLD ERROR: RPN  Expression is invalid! THold:'E1T14 NX7010 CORE1 - Traffic - Null0  [traffic_in]', Value:'0',  Expression:'\|ds:traffic_in\|,8,*,1000000,/,\|query_ifHighSpeed\|,/,100,*'
2017/09/02 08:15:22 - THOLD ERROR: RPN  Expression is invalid! THold:'E1Z05R1046-VDX6740-A - Traffic -  10.255.4.206 - eth0 [traffic_out]', Value:'0',  Expression:'\|ds:traffic_out\|,8,*,1000000,/,\|query_ifHighSpeed\|,/,100,*'
2017/09/02 08:15:21 - THOLD ERROR: RPN  Expression is invalid! THold:'E1Z05R1046-VDX6740-A - Traffic -  10.255.4.206 - eth0 [traffic_in]', Value:'0',  Expression:'\|ds:traffic_in\|,8,*,1000000,/,\|query_ifHighSpeed\|,/,100,*'
2017/09/02 08:15:21 - THOLD ERROR: RPN  Expression is invalid! THold:'E1Z05R0548-VDX6740T-A - Traffic -  10.255.4.116 - eth0 [traffic_out]', Value:'0',  Expression:'\|ds:traffic_out\|,8,*,1000000,/,\|query_ifHighSpeed\|,/,100,*'
2017/09/02 08:15:21 - THOLD ERROR: RPN  Expression is invalid! THold:'E1Z05R0548-VDX6740T-A - Traffic -  10.255.4.116 - eth0 [traffic_in]', Value:'0',  Expression:'\|ds:traffic_in\|,8,*,1000000,/,\|query_ifHighSpeed\|,/,100,*'
2017/09/02 08:15:21 - THOLD ERROR: RPN  Expression is invalid! THold:'E1T13-CP13500-TIER1FW2 - Traffic -  bond3.3720 - Common Services DMZ 2 - Skype for Busine [traffic_ou',  Value:'673.4',  Expression:'\|ds:traffic_out\|,8,*,1000000,/,\|query_ifHighSpeed\|,/,100,*'
2017/09/02 08:15:21 - THOLD ERROR: RPN  Expression is invalid! THold:'E1Z05R0748-VDX6740T-A - Traffic -  10.255.4.118 - eth0 [traffic_out]', Value:'0',  Expression:'\|ds:traffic_out\|,8,*,1000000,/,\|query_ifHighSpeed\|,/,100,*'
2017/09/02 08:15:21 - THOLD ERROR: RPN  Expression is invalid! THold:'E1T13-CP13500-TIER1FW2 - Traffic -  bond3.3720 - Common Services DMZ 2 - Skype for Busine [traffic_in',  Value:'594.63333333333',

**Comment by cigamit** [comment]
Those RPN's are invalid (or at least how they appear in the log).  For example:

`|ds:traffic_out|,8,,1000000,/,|query_ifHighSpeed|,/,100,`

I think that there is supposed to be an asterik ("*") after the `8,`, that is missing.  Also, the RPN ends with a comma which is not valid.  Can you paste the RPN from the thold?

**Comment by cigamit** [comment]
Ope, I see the issue now.  First, GitHub is masking those asterisks.  Second the pipes have been escaped around the |ds:traffic_out| and |query_ifHighSpeed|.

**Comment by cigamit** [comment]
Take another crack using the latest commit.  Need to get rid of those escape characters.  You may be able to edit them out of the template too.

**Comment by ikorzha** [comment]
With latest patch it is definitely getting better. However I'm still getting a ton of "RPN Expression is invalid!" in log see blow.  I'm still unclear is my RPN expression incorrect (if so can you point me to what exactly is wrong or is it thold that doesn't handle this RPN properly..?
Out of 10000 of traffic in and traffic out tholds it only errors out on 20 that have no traffic  and logical bond interfaces that have traffic....

Please assist if you can.

![template](https://user-images.githubusercontent.com/11211789/29997620-a08f351e-8fe5-11e7-98d8-6e9cb9c66325.gif)



2017/09/02  13:40:37 - THOLD ERROR: RPN Expression is invalid!  THold:'E1Z05R0548-VDX6740T-A - Traffic - 10.255.4.116 - eth0  [traffic_in]', Value:'0',  Expression:'\|ds:traffic_in\|,8,*,1000000,/,\|query_ifHighSpeed\|,/,100,*'
--
2017/09/02 13:40:31 - THOLD ERROR: RPN  Expression is invalid! THold:'E1Z07R1046-VDX6740-A - Traffic -  10.255.4.210 - eth0 [traffic_out]', Value:'0',  Expression:'\|ds:traffic_out\|,8,*,1000000,/,\|query_ifHighSpeed\|,/,100,*'
2017/09/02 13:40:31 - THOLD ERROR: RPN  Expression is invalid! THold:'E1Z07R1046-VDX6740-A - Traffic -  10.255.4.210 - eth0 [traffic_in]', Value:'0',  Expression:'\|ds:traffic_in\|,8,*,1000000,/,\|query_ifHighSpeed\|,/,100,*'
2017/09/02 13:40:28 - THOLD ERROR: RPN  Expression is invalid! THold:'E1Z07R0146-VDX6740-A - Traffic -  10.255.4.139 - eth0 [traffic_out]', Value:'0',  Expression:'\|ds:traffic_out\|,8,*,1000000,/,\|query_ifHighSpeed\|,/,100,*'
2017/09/02 13:40:28 - THOLD ERROR: RPN  Expression is invalid! THold:'E1Z07R0146-VDX6740-A - Traffic -  10.255.4.139 - eth0 [traffic_in]', Value:'0',  Expression:'\|ds:traffic_in\|,8,*,1000000,/,\|query_ifHighSpeed\|,/,100,*'
2017/09/02 13:40:26 - THOLD ERROR: RPN  Expression is invalid! THold:'E1Z05R0748-VDX6740T-A - Traffic -  10.255.4.118 - eth0 [traffic_out]', Value:'0',  Expression:'\|ds:traffic_out\|,8,*,1000000,/,\|query_ifHighSpeed\|,/,100,*'
2017/09/02 13:40:26 - THOLD ERROR: RPN  Expression is invalid! THold:'E1Z05R0748-VDX6740T-A - Traffic -  10.255.4.118 - eth0 [traffic_in]', Value:'0',  Expression:'\|ds:traffic_in\|,8,*,1000000,/,\|query_ifHighSpeed\|,/,100,*'

**Comment by cigamit** [comment]
Okay, we just moved the branch to 'develop'.  So, from the develop branch, pull the latest thold_functions.php, and the root cause will be exposed.  I'm guessing that ifHighSpeed is '0'.  Let's see if that's the case.  If so, we have to hack something up.

**Comment by ikorzha** [comment]
Here is the latest error msg log based on your last commit:

![errors-2](https://user-images.githubusercontent.com/11211789/29997832-87147634-8feb-11e7-833d-928d76dae908.gif)

**Comment by cigamit** [comment]
I've pushed one more version that will add additional logging.  Please run with this and paste the log.

**Comment by ikorzha** [comment]
Thank you for latest push: log screenshot below, log is huge this is just a quick screenshot.

![latest-commit](https://user-images.githubusercontent.com/11211789/30004420-e3c29c88-909c-11e7-934f-2bba262c4fd8.gif)

**Comment by cigamit** [comment]
Let's see how clean it is now.  Also, please attach a copy of the graph in question.

**Comment by cigamit** [comment]
Just a note, it looks like both the `|ds:traffic_in|` and the `|query_ifHighSpeed|` are set to 0.

**Comment by cigamit** [comment]
So, we might be able to approximate by 0/0 = 0 (which in theoretically is not correct, but close enough if you put the data in context.  A physicist or mathematician might argue though).

**Comment by ikorzha** [comment]
As requested results of latest commit:  Personally I'm more concerned that it errors on bond interfaces with non "0" traffic.  
I have attached" bond3 - DMZ" graph which is non 0 and THOLD log error for it..

![latest-commit](https://user-images.githubusercontent.com/11211789/30004684-dfbafa18-90a1-11e7-8b66-de1bb500c31e.gif)

![latest-commit-graph](https://user-images.githubusercontent.com/11211789/30004650-57c47fda-90a1-11e7-901d-90b5495df038.gif)

**Comment by cigamit** [comment]
Try again.  I am adding again more debugging.  Additionally, I'm assuming that any device that comes back with a value of 0, for example a bond interface, that the speed will be 10GE.  Do you think that needs to be a setting?

**Comment by ikorzha** [comment]
10GB assumption for bond is good and for any other interface that comes back as 0. I agree with approach.
Latest commit has introduced a new bug or 2 :) Lots errorsin the log.
![latest-commit](https://user-images.githubusercontent.com/11211789/30006593-b076cec6-90c9-11e7-8e5f-9bdc066a7a86.gif)

**Comment by cigamit** [comment]
Okay, get back at it tomorrow.

**Comment by cigamit** [comment]
Try again and submit your log details.

**Comment by ikorzha** [comment]
Thank you for your commitment, I believe the last commit has resolved the issue.  Please close the issue if nothing else!
![latest-commit](https://user-images.githubusercontent.com/11211789/30027434-fdabf2ea-914e-11e7-8ac8-246bf4f30980.gif)

**Comment by cigamit** [comment]
Okay, I'm going to make a few more changes related to that 10GE setting.  Going to make it a setting on the thresholds page.  Also, change the CPUTime to wall clock time.  Need to make that faster too.  452 seconds for only 15k thresholds is a bitch.

Are you using the thold daemon?  Would you be willing to assist on optimizing the run time with me?

**Comment by cigamit** [comment]
Ope, it looks like thold daemon already.

**Comment by cigamit** [comment]
Okay, just made the setting a setting defaulting to 10GE.

**Comment by cigamit** [comment]
If you want to collaborate on improving performance, just open another ticket.  Going to close this one.

**Comment by ikorzha** [comment]
Thank your for your work! I absolutely love to work with you on performance improvement. In fact mysefl and my brother who is the developer has made improvements to thold daemon since the original wasn't working properly. It is not ideal and I would love working with you on improving thold performance on large system such as myself,  Currently I only have 16K tholds, which represent 40% of my install base.  Over next month I will migrate additional devices  to my "CactiONE" install base.
In any case I will open additional case/s to work with you on improvements.
Thank you in advance!
